import numpy as np
import math

class ReverseScalarDecoder:
    """
    Decodes an SDR back into a continuous scalar value.
    Assumes the SDR was generated by a contiguous chunk or finds the center of mass.
    """
    def __init__(self, size, min_val, max_val):
        self.size = size
        self.min_val = min_val
        self.max_val = max_val
        self.range = max_val - min_val

    def decode(self, indices):
        if len(indices) == 0:
            return self.min_val # Default if no bits active

        # Center of mass of the active indices
        mean_idx = np.mean(indices)

        # Map back to value space
        val = self.min_val + (mean_idx / (self.size - 1)) * self.range
        return min(max(val, self.min_val), self.max_val)

class ReverseCyclicDecoder:
    """
    Decodes an SDR back into a cyclic value (like an angle).
    Uses circular mean to handle wrap-around correctly.
    """
    def __init__(self, size, min_val=0.0, max_val=2*math.pi):
        self.size = size
        self.min_val = min_val
        self.max_val = max_val
        self.range = max_val - min_val

    def decode(self, indices):
        if len(indices) == 0:
            return self.min_val

        # Convert indices to angles on a unit circle
        angles = (indices / self.size) * 2 * math.pi

        # Compute circular mean
        sin_sum = np.sum(np.sin(angles))
        cos_sum = np.sum(np.cos(angles))

        mean_angle = math.atan2(sin_sum, cos_sum)
        if mean_angle < 0:
            mean_angle += 2 * math.pi

        # Map back to desired range
        val = self.min_val + (mean_angle / (2 * math.pi)) * self.range
        return val

def action_decode(encoding_indices, sp_size, num_cells=None):
    """
    Takes the active indices from HTM output (which could be the Temporal Memory indices,
    which have length sp_size * cells_per_col, or Spatial Pooler indices).

    If indices are from TM, we map them back to SP columns first.
    Then we split the SP columns into a target coordinates portion, an angle portion and a ship portion.
    """
    if num_cells is not None:
        columns = indices_to_columns(encoding_indices, num_cells)
    else:
        columns = np.array(encoding_indices)

    # Split the SP columns into 4 portions:
    # 1. Target Planet Selection X (0 to 1000)
    # 2. Target Planet Selection Y (0 to 1000)
    # 3. Action Angle (0 to 2pi)
    # 4. Ships % (0 to 1)
    quarter_size = sp_size // 4

    target_x_cols = columns[columns < quarter_size]
    target_y_cols = columns[(columns >= quarter_size) & (columns < 2*quarter_size)] - quarter_size
    angle_cols = columns[(columns >= 2*quarter_size) & (columns < 3*quarter_size)] - 2*quarter_size
    ship_cols = columns[columns >= 3*quarter_size] - 3*quarter_size

    # Decode Target Selection (assume map size max 1000 for x and y bounds, Kaggle orbit wars is generally bounded)
    target_x_decoder = ReverseScalarDecoder(quarter_size, 0.0, 1000.0)
    target_y_decoder = ReverseScalarDecoder(quarter_size, 0.0, 1000.0)
    target_x = target_x_decoder.decode(target_x_cols)
    target_y = target_y_decoder.decode(target_y_cols)

    # Decode Action Angle
    angle_decoder = ReverseCyclicDecoder(quarter_size, 0, 2*math.pi)
    angle = angle_decoder.decode(angle_cols)

    # Decode Ship %
    ship_decoder = ReverseScalarDecoder(quarter_size, 0.0, 1.0)
    ship_pct = ship_decoder.decode(ship_cols)

    return target_x, target_y, angle, ship_pct

def indices_to_columns(tm_indices, cells_per_col):
    cols = np.array(tm_indices) // cells_per_col
    return np.unique(cols)
