import numpy as np
import math

class ReverseScalarDecoder:
    """
    Decodes an SDR back into a continuous scalar value.
    Assumes the SDR was generated by a contiguous chunk or finds the center of mass.
    """
    def __init__(self, size, min_val, max_val):
        self.size = size
        self.min_val = min_val
        self.max_val = max_val
        self.range = max_val - min_val

    def decode(self, indices):
        if len(indices) == 0:
            return self.min_val # Default if no bits active

        # Center of mass of the active indices
        mean_idx = np.mean(indices)

        # Map back to value space
        val = self.min_val + (mean_idx / (self.size - 1)) * self.range
        return min(max(val, self.min_val), self.max_val)

class ReverseCyclicDecoder:
    """
    Decodes an SDR back into a cyclic value (like an angle).
    Uses circular mean to handle wrap-around correctly.
    """
    def __init__(self, size, min_val=0.0, max_val=2*math.pi):
        self.size = size
        self.min_val = min_val
        self.max_val = max_val
        self.range = max_val - min_val

    def decode(self, indices):
        if len(indices) == 0:
            return self.min_val

        # Convert indices to angles on a unit circle
        angles = (indices / self.size) * 2 * math.pi

        # Compute circular mean
        sin_sum = np.sum(np.sin(angles))
        cos_sum = np.sum(np.cos(angles))

        mean_angle = math.atan2(sin_sum, cos_sum)
        if mean_angle < 0:
            mean_angle += 2 * math.pi

        # Map back to desired range
        val = self.min_val + (mean_angle / (2 * math.pi)) * self.range
        return val

def action_decode(encoding_indices, sp_size, num_cells=None):
    """
    Takes the active indices from HTM output (which could be the Temporal Memory indices,
    which have length sp_size * cells_per_col, or Spatial Pooler indices).

    If indices are from TM, we map them back to SP columns first.
    Then we split the SP columns into an angle portion and a ship portion.
    """
    if num_cells is not None:
        # Map TM cells back to SP columns
        # tm_size = sp_size * cells_per_col
        # column_idx = cell_idx // cells_per_col
        columns = indices_to_columns(encoding_indices, num_cells)
    else:
        columns = np.array(encoding_indices)

    # Assuming SP output size is e.g. 200 bits total for action
    # First half = Angle, Second half = Ships %
    half_size = sp_size // 2

    angle_cols = columns[columns < half_size]
    ship_cols = columns[columns >= half_size] - half_size

    # We decode Angle to 0 -> 2pi
    angle_decoder = ReverseCyclicDecoder(half_size, 0, 2*math.pi)
    angle = angle_decoder.decode(angle_cols)

    # We decode Ship % to 0 -> 100% (or fraction 0 -> 1)
    ship_decoder = ReverseScalarDecoder(half_size, 0.0, 1.0)
    ship_pct = ship_decoder.decode(ship_cols)

    return angle, ship_pct

def indices_to_columns(tm_indices, cells_per_col):
    cols = np.array(tm_indices) // cells_per_col
    return np.unique(cols)
